const IMG={pink:'https://lh3.googleusercontent.com/aida-public/AB6AXuBiteyRrwWaEe9HCsZnX409TYgRzZ_Jqvr3syXH8VwH3gqLe_eJdTrTwAcDQUcWhjtvFpcED2LASjVjpv3t9-NeGqFeMnXMQYy_Dq3B_hgtEZ4yz6PPJmaUXgMYXM_8Xmj3tLDIcdzkGYis5FLUfpWU8i1Y3fLyLpm14XIeH2cEUAlE1NZeUKB8B1CS7jaC9opXE4besxx0FV14srC7MPGgHRc_h7yI5tPzrb_oLO5i9d_pkirp3WSEycG0pLPRQih7jGhe3e1XAIEe',suit:'https://lh3.googleusercontent.com/aida-public/AB6AXuD7PMu0ZEQF67yLbB902XsBlic3EAgsbjbbEvxvx2rXLlIU9189bO4bWb5X50NeazSFflN1CTvtyE7SXQQ2-AxQip31Ul9eBW6loMpi3vifeTW0HFudEdkNl_m8MpdB-I_vA1ScrdxDcocHv3-o7EucK9QyHLgR7Xa7I4WbqS-DkSskzhSTBQT14FmqFf3CkaVmdQ4ruraoU_4403cQwbNq9hNEWl5VGOpR5pzgO67DRVLSZyCFgLabtw6oUuhub-sedl2iToMtIr_y',red:'https://lh3.googleusercontent.com/aida-public/AB6AXuCgNScyomn8qQQD9tuo5VOeFLe4j0FKyf-4IsXR2NYdDJcwVCEez-9MWUdXUmgLA6HsmlRhND5VA4uk9VG9hsLMFBf79Fg-PF1-H_scuuR6c5agPLq_wge8-Qcc_5qeEoIckrJfZ8oQxTMtDrkx0FXOyFSFYITEsvkQa3c5C212cPdjbLBtRgnAYNPSNzQ1eQ4KvBX1BRDIo6LqbDcQejavo-vP4JXLskEIM-m6d1upMnIR3QOp0WJYtX8EBAXzFfW7bFMX5hNGixJp',mauve:'https://lh3.googleusercontent.com/aida-public/AB6AXuDRwxBGZJZO6ITgybmr06WguHWAeS-qu0_Oqz7pl8ZbwuAYoUUoEbeYYLAxY41PltFWQJxW88JNRlFmxI2SUOvf-5AKesxBMKCEhCmfBeS9RNQIb9Q493FsJL8xxFoQO9mGAd9ZlnguY4Am1WphX2vI0vczVC9n36jXTXsVVGVH33TvcPyxDvGLNcY0BXb2-jm14qVuuZWpPqToVpYozR_9A1NFgpmRrZTdFYfFCr8TRWrN-1jcjVHqsv3m05KKNCkjiNuxyeuoo1sW'};
const defaults=[
 {id:'p1',name:{uz:'Romantik ko‘ylak',ru:'Романтичное платье',en:'Romantic dress'},category:'dresses',price:550000,image:IMG.pink,sizes:['S','M','L'],popular:true,stock:8},
 {id:'p2',name:{uz:'Zarafshon to‘plam',ru:'Комплект Zarafshon',en:'Zarafshon set'},category:'sets',price:670000,image:IMG.suit,sizes:['S','M','L'],isNew:true,stock:5},
 {id:'p3',name:{uz:'Ipak kechki ko‘ylak',ru:'Шёлковое вечернее платье',en:'Silk evening dress'},category:'dresses',price:780000,oldPrice:850000,image:IMG.red,sizes:['S','M'],trending:true,stock:3},
 {id:'p4',name:{uz:'Kundalik libos',ru:'Повседневное платье',en:'Everyday dress'},category:'women',price:420000,image:IMG.mauve,sizes:['S','M','L','XL'],popular:true,stock:12},
 {id:'p5',name:{uz:'Bahoriy libos',ru:'Весеннее платье',en:'Spring dress'},category:'dresses',price:490000,image:IMG.pink,sizes:['S','M','L'],isNew:true,stock:7},
 {id:'p6',name:{uz:'Qizlar uchun libos',ru:'Платье для девочек',en:'Girls dress'},category:'kids',price:350000,image:IMG.mauve,sizes:['4Y','6Y','8Y'],kids:true,stock:6},
 {id:'p7',name:{uz:'Nafis sumka',ru:'Изящная сумка',en:'Elegant bag'},category:'accessories',price:290000,image:IMG.suit,sizes:[],stock:4},
 {id:'p8',name:{uz:'Blossom ko‘ylak',ru:'Платье Blossom',en:'Blossom dress'},category:'dresses',price:620000,image:IMG.red,sizes:['S','M','L'],trending:true,stock:4}
];
const tr={uz:{'nav.home':'Bosh sahifa','nav.catalog':'Katalog','nav.new':'Yangi kelganlar','nav.popular':'Ommabop','nav.about':'Biz haqimizda','nav.contact':'Aloqa','nav.favorites':'Sevimlilar','nav.admin':'Administrator uchun','hero.line1':'Har ayolning','hero.line2':'o‘z uslubi bor','hero.sub':'KIYARI bilan o‘zingizni ifoda eting','hero.catalog':'Katalogni ko‘rish','hero.telegram':'Telegramga o‘tish ↗','hero.scroll':'Sahifani pastga suring','catalog.title':'Katalog','catalog.sub':'Sevimli uslubingizni toping','favorites.title':'Mening sevimlilarim','favorites.empty':'Hali sevimli mahsulot tanlanmagan','new.title':'Yangi kelganlar','new.sub':'Siz uchun eng yangi kolleksiyalar','popular.title':'Ommabop mahsulotlar','popular.sub':'Xaridorlarimiz eng ko‘p tanlagan liboslar','about.title':'Biz haqimizda','about.sub':'Har detalda nafislik','about.text':'KIYARI — zamonaviy va nafis ayollar kiyimlari do‘koni. Biz har bir ayol o‘z uslubini topishi, o‘zini chiroyli, ishonchli va betakror his qilishi uchun sifatli liboslar tanlaymiz.','about.quality':'Premium sifat','about.design':'Zamonaviy dizayn','about.style':'Shaxsiy uslub','about.note':'Har bir detalda mehr bor','contact.title':'Biz bilan bog‘laning','contact.address':'Toshkent, O‘zbekiston','contact.name':'Ismingiz','contact.phone':'Telefon raqamingiz','contact.message':'Xabaringiz','contact.send':'Yuborish','footer.phrase':'Har ayol go‘zalligini KIYARI bilan kashf eting.','footer.brand':'Brend','footer.rights':'Barcha huquqlar himoyalangan.','admin.title':'Admin panel','admin.login':'Mahsulotlarni boshqarish uchun parolni kiriting.','admin.password':'Parol','admin.enter':'Kirish','admin.name':'Mahsulot nomi','admin.category':'Turkum','admin.price':'Narxi','admin.oldPrice':'Eski narxi','admin.image':'Rasm yuklash','admin.sizes':'O‘lchamlar (S,M,L)','admin.stock':'Ombordagi soni','admin.flags':'Belgilar','admin.save':'Mahsulotni saqlash'},
ru:{'nav.home':'Главная','nav.catalog':'Каталог','nav.new':'Новинки','nav.popular':'Популярное','nav.about':'О нас','nav.contact':'Контакты','nav.favorites':'Избранное','nav.admin':'Для администратора','hero.line1':'У каждой женщины','hero.line2':'есть свой стиль','hero.sub':'Выразите себя вместе с KIYARI','hero.catalog':'Смотреть каталог','hero.telegram':'Перейти в Telegram ↗','hero.scroll':'Листайте вниз','catalog.title':'Каталог','catalog.sub':'Найдите свой любимый стиль','favorites.title':'Моё избранное','favorites.empty':'Вы пока не выбрали избранные товары','new.title':'Новинки','new.sub':'Самые свежие коллекции для вас','popular.title':'Популярные товары','popular.sub':'Самые любимые модели наших клиентов','about.title':'О нас','about.sub':'Изысканность в каждой детали','about.text':'KIYARI — магазин современной и элегантной женской одежды. Мы подбираем качественные образы, чтобы каждая женщина чувствовала себя красивой, уверенной и неповторимой.','about.quality':'Премиум качество','about.design':'Современный дизайн','about.style':'Личный стиль','about.note':'В каждой детали — любовь','contact.title':'Свяжитесь с нами','contact.address':'Ташкент, Узбекистан','contact.name':'Ваше имя','contact.phone':'Номер телефона','contact.message':'Сообщение','contact.send':'Отправить','footer.phrase':'Откройте свою красоту вместе с KIYARI.','footer.brand':'Бренд','footer.rights':'Все права защищены.'},
en:{'nav.home':'Home','nav.catalog':'Catalog','nav.new':'New Stock','nav.popular':'Popular','nav.about':'About Us','nav.contact':'Contact','nav.favorites':'Favorites','nav.admin':'Administrator','hero.line1':'Every woman has','hero.line2':'her own style','hero.sub':'Express yourself with KIYARI','hero.catalog':'View Catalog','hero.telegram':'Open Telegram ↗','hero.scroll':'Scroll to discover','catalog.title':'Catalog','catalog.sub':'Find your favorite style','favorites.title':'My Favorites','favorites.empty':'No favorite products yet','new.title':'New Stock','new.sub':'Fresh new collections for you','popular.title':'Popular Products','popular.sub':'The most loved pieces by our customers','about.title':'About Us','about.sub':'Elegance in every detail','about.text':'KIYARI is a modern and elegant women’s clothing store. We select quality pieces so every woman can feel beautiful, confident, and unique.','about.quality':'Premium quality','about.design':'Modern design','about.style':'Personal style','about.note':'Love in every detail','contact.title':'Contact Us','contact.address':'Tashkent, Uzbekistan','contact.name':'Your name','contact.phone':'Phone number','contact.message':'Message','contact.send':'Send','footer.phrase':'Discover your beauty with KIYARI.','footer.brand':'Brand','footer.rights':'All rights reserved.'}};
let lang=localStorage.getItem('kiyari_language')||'uz';let products=JSON.parse(localStorage.getItem('kiyari_products')||'null')||defaults;let favorites=JSON.parse(localStorage.getItem('kiyari_favorites')||'[]');let filter='all';
const t=k=>tr[lang][k]||tr.uz[k]||k, money=n=>new Intl.NumberFormat(lang==='ru'?'ru-RU':'uz-UZ').format(n)+' so‘m';
function persist(){localStorage.setItem('kiyari_products',JSON.stringify(products));localStorage.setItem('kiyari_favorites',JSON.stringify(favorites))}
function productName(p){return typeof p.name==='string'?p.name:(p.name[lang]||p.name.uz)}
function card(p){const saved=favorites.includes(p.id);return `<article class="product-card"><div class="product-image"><img loading="lazy" src="${p.image}" alt="${productName(p)}"><button class="favorite ${saved?'active':''}" data-favorite="${p.id}" aria-label="Favorite">${saved?'♥':'♡'}</button>${p.isNew?'<span class="badge">NEW</span>':''}</div><div class="product-info"><h3>${productName(p)}</h3><div><span class="price">${money(p.price)}</span>${p.oldPrice?`<span class="old-price">${money(p.oldPrice)}</span>`:''}</div><p class="meta">${p.sizes?.join(' · ')||'ONE SIZE'} · ${p.stock||0} IN STOCK</p><a class="telegram-product" target="_blank" href="https://t.me/KIYARI_UZ">TELEGRAM ↗</a></div></article>`}
function draw(){const visible=filter==='all'?products:products.filter(p=>p.category===filter||p[filter]);document.querySelector('#catalogGrid').innerHTML=visible.map(card).join('');const fav=products.filter(p=>favorites.includes(p.id));document.querySelector('#favoritesGrid').innerHTML=fav.length?fav.map(card).join(''):`<div class="empty"><b>♡</b>${t('favorites.empty')}</div>`;document.querySelector('#newGrid').innerHTML=products.filter(p=>p.isNew).map(card).join('');document.querySelector('#popularGrid').innerHTML=products.filter(p=>p.popular).map(card).join('');document.querySelector('#favoriteCount').textContent=favorites.length;drawAdmin()}
const cats={all:{uz:'Barchasi',ru:'Все',en:'All'},dresses:{uz:'Ko‘ylaklar',ru:'Платья',en:'Dresses'},sets:{uz:'To‘plamlar',ru:'Комплекты',en:'Sets'},kids:{uz:'Bolalar',ru:'Дети',en:'Kids'},accessories:{uz:'Aksessuarlar',ru:'Аксессуары',en:'Accessories'},isNew:{uz:'Yangi',ru:'Новинки',en:'New'},popular:{uz:'Ommabop',ru:'Популярное',en:'Popular'},trending:{uz:'Trend',ru:'Тренд',en:'Trending'}};
function drawFilters(){document.querySelector('#filters').innerHTML=Object.entries(cats).map(([k,v])=>`<button class="filter ${filter===k?'active':''}" data-filter="${k}">${v[lang]}</button>`).join('')}
function setLanguage(next){lang=next;localStorage.setItem('kiyari_language',lang);document.documentElement.lang=lang;document.querySelectorAll('[data-t]').forEach(el=>el.textContent=t(el.dataset.t));document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));drawFilters();draw()}
document.addEventListener('click',e=>{const f=e.target.closest('[data-favorite]');if(f){const id=f.dataset.favorite;favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];persist();draw()}const ft=e.target.closest('[data-filter]');if(ft){filter=ft.dataset.filter;drawFilters();draw()}const l=e.target.closest('[data-lang]');if(l)setLanguage(l.dataset.lang)});
document.querySelector('#menuButton').onclick=()=>document.querySelector('#navLinks').classList.toggle('open');document.querySelectorAll('.nav-links a').forEach(a=>a.onclick=()=>document.querySelector('#navLinks').classList.remove('open'));
for(let i=0;i<48;i++){const s=document.createElement('span');s.style.cssText=`left:${Math.random()*100}%;top:${10+Math.random()*85}%;animation-delay:${Math.random()*-6}s;transform:scale(${.4+Math.random()})`;document.querySelector('#particles').append(s)}
const ambient=document.querySelector('#ambientWorld');
if(ambient){
 const colors=['#c51e3a','#ef6d87','#8b315f','#d69ab5','#76608a'];
 for(let i=0;i<82;i++){
  const d=document.createElement('i');d.className='ambient-dust';
  const size=(2+Math.random()*5).toFixed(1)+'px';
  d.style.cssText=`--x:${(Math.random()*100).toFixed(2)}%;--y:${(Math.random()*100).toFixed(2)}%;--size:${size};--color:${colors[i%colors.length]};--opacity:${(.18+Math.random()*.38).toFixed(2)};--delay:${(-Math.random()*18).toFixed(1)}s;--duration:${(8+Math.random()*13).toFixed(1)}s;--drift-x:${(-35+Math.random()*70).toFixed(1)}px`;
  ambient.append(d)
 }
 const flowerColors=['#d51d43','#ef7890','#a94e73','#8f5a91'];
 const flowerSvg='<svg viewBox="0 0 32 32"><path class="heart-petal" d="M16 14C8 11 7 3 12 2c3-.7 4 2 4 4 0-2 1-4.7 4-4 5 1 4 9-4 12Z"/><path class="heart-petal" d="M18 16c3-8 11-9 12-4 .7 3-2 4-4 4 2 0 4.7 1 4 4-1 5-9 4-12-4Z"/><path class="heart-petal" d="M16 18c8 3 9 11 4 12-3 .7-4-2-4-4 0 2-1 4.7-4 4-5-1-4-9 4-12Z"/><path class="heart-petal" d="M14 16c-3 8-11 9-12 4-.7-3 2-4 4-4-2 0-4.7-1-4-4 1-5 9-4 12 4Z"/><circle class="flower-core" cx="16" cy="16" r="3.2"/></svg>';
 for(let i=0;i<24;i++){
  const f=document.createElement('span');f.className='ambient-flower';f.innerHTML=flowerSvg;
  f.style.cssText=`--x:${(Math.random()*100).toFixed(2)}%;--y:${(Math.random()*100).toFixed(2)}%;--flower-size:${(9+Math.random()*17).toFixed(1)}px;--flower-color:${flowerColors[i%flowerColors.length]};--flower-opacity:${(.3+Math.random()*.38).toFixed(2)};--delay:${(-Math.random()*20).toFixed(1)}s;--duration:${(12+Math.random()*14).toFixed(1)}s;--drift-x:${(-45+Math.random()*90).toFixed(1)}px`;
  ambient.append(f)
 }
}
const dressSource=document.querySelector('#dressSource'),dressCanvas=document.querySelector('#heroDress');
if(dressSource&&dressCanvas){
 const keyDress=()=>{const w=dressSource.naturalWidth,h=dressSource.naturalHeight;dressCanvas.width=w;dressCanvas.height=h;const ctx=dressCanvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(dressSource,0,0,w,h);const frame=ctx.getImageData(0,0,w,h),px=frame.data;for(let i=0;i<px.length;i+=4){const r=px[i],g=px[i+1],b=px[i+2],green=g-Math.max(r,b);if(g>105&&green>22){const alpha=Math.max(0,255-(green-22)*5.2);px[i+3]=Math.min(px[i+3],alpha);if(alpha>0){px[i]=Math.min(255,r+green*.1);px[i+1]=Math.max(0,g-green*.78);px[i+2]=Math.min(255,b+green*.08)}}}ctx.clearRect(0,0,w,h);ctx.putImageData(frame,0,0)};dressSource.complete?keyDress():dressSource.addEventListener('load',keyDress,{once:true})
}
document.addEventListener('pointerdown',e=>{const target=e.target.closest('.button,.filter');if(!target)return;target.classList.remove('press');void target.offsetWidth;target.classList.add('press');setTimeout(()=>target.classList.remove('press'),600)});
function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
document.querySelector('#contactForm').onsubmit=e=>{e.preventDefault();toast(lang==='ru'?'Спасибо! Ваше сообщение готово.':lang==='en'?'Thank you! Your message is ready.':'Rahmat! Xabaringiz tayyor.');e.target.reset()};
const dialog=document.querySelector('#adminDialog'),login=document.querySelector('#loginView'),form=document.querySelector('#productForm');document.querySelector('#adminOpen').onclick=()=>dialog.showModal();document.querySelector('#adminClose').onclick=()=>dialog.close();
// This admin password is for demo only. For production, replace with real backend authentication.
function unlock(){login.hidden=true;form.hidden=false;localStorage.setItem('kiyari_admin_unlocked','true');drawAdmin()}document.querySelector('#adminLogin').onclick=()=>document.querySelector('#adminPassword').value==='12345'?unlock():toast('Parol noto‘g‘ri');if(localStorage.getItem('kiyari_admin_unlocked')==='true')unlock();
form.onsubmit=async e=>{e.preventDefault();const d=new FormData(form),file=d.get('image'),existing=products.find(p=>p.id===d.get('id'));let image=existing?.image||IMG.pink;if(file?.size)image=await new Promise(r=>{const fr=new FileReader();fr.onload=()=>r(fr.result);fr.readAsDataURL(file)});const p={id:d.get('id')||'p'+Date.now(),name:{uz:d.get('name'),ru:d.get('name'),en:d.get('name')},category:d.get('category'),price:+d.get('price'),oldPrice:+d.get('oldPrice')||0,image,sizes:d.get('sizes').split(',').map(x=>x.trim()).filter(Boolean),stock:+d.get('stock'),popular:d.has('popular'),trending:d.has('trending'),kids:d.has('kids'),isNew:d.has('isNew')};products=existing?products.map(x=>x.id===p.id?p:x):[p,...products];persist();form.reset();draw();toast('Mahsulot saqlandi')};
function drawAdmin(){const el=document.querySelector('#adminProducts');if(!el)return;el.innerHTML='<h3>Mahsulotlar</h3>'+products.map(p=>`<div class="admin-item"><span>${productName(p)}</span><span><button data-edit="${p.id}">Edit</button><button data-delete="${p.id}">Delete</button></span></div>`).join('');el.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{products=products.filter(p=>p.id!==b.dataset.delete);favorites=favorites.filter(id=>id!==b.dataset.delete);persist();draw()});el.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const p=products.find(x=>x.id===b.dataset.edit);for(const k of ['id','category','price','oldPrice','stock'])form.elements[k].value=p[k]||'';form.elements.name.value=productName(p);form.elements.sizes.value=p.sizes?.join(',')||'';for(const k of ['popular','trending','kids','isNew'])form.elements[k].checked=!!p[k];form.scrollTo({top:0,behavior:'smooth'})})}
if(window.gsap&&!matchMedia('(prefers-reduced-motion: reduce)').matches){
 gsap.registerPlugin(ScrollTrigger);
 gsap.set('.hero-copy>*',{opacity:0,y:34});gsap.set('.hero-dress',{opacity:0,scale:.18,rotationY:-540,rotationZ:-24,transformOrigin:'50% 48%'});gsap.set('.silk-dragon',{opacity:.95});
 const tl=gsap.timeline({defaults:{ease:'power2.inOut'},scrollTrigger:{trigger:'.hero-scroll',start:'top top',end:'bottom bottom',scrub:.65,snap:{snapTo:[0,.22,.5,.76,1],duration:{min:.12,max:.36},delay:.08,ease:'power1.inOut'}}});
 tl.fromTo('.hero-bg',{scale:1.08},{scale:1.015,duration:1.1},0)
   .to('.silk-one',{left:'48%',top:'43%',rotation:420,scale:.68,duration:1.8},.15)
   .to('.silk-two',{right:'17%',top:'43%',rotation:-430,scale:.64,duration:1.8},.15)
   .to('.silk-three',{left:'47%',bottom:'42%',rotation:-400,scale:.58,duration:1.8},.15)
   .to('.silk-four',{right:'18%',bottom:'41%',rotation:440,scale:.62,duration:1.8},.15)
   .to('.vortex-core',{opacity:1,rotation:540,scale:1.1,duration:1.65},.4)
   .to('.vortex-core i',{rotation:(i)=>i%2?720:-720,stagger:.05,duration:1.8},.4)
   .to('.hero-dress',{opacity:1,scale:1.13,rotationY:0,rotationZ:360,duration:2.25,ease:'power3.out'},1.25)
   .to('.silk-dragon',{scale:.05,opacity:0,filter:'blur(16px)',rotation:'+=380',stagger:.05,duration:1.1},2.3)
   .to('.vortex-core',{scale:.25,opacity:0,rotation:900,duration:1},2.45)
   .to('.hero-dress',{scale:1,rotationZ:360,y:0,duration:.8,ease:'back.out(1.7)'},2.75)
   .to('.hero-copy>*',{opacity:1,y:0,stagger:.1,duration:.75},2.8)
   .fromTo('.corner-bloom',{opacity:.1,scale:.5},{opacity:.85,scale:1,stagger:.08,duration:.8},2.5);
 gsap.utils.toArray('.reveal').forEach(el=>gsap.to(el,{opacity:1,y:0,duration:1,scrollTrigger:{trigger:el,start:'top 88%'}}));
 gsap.utils.toArray('.product-card').forEach((el,i)=>gsap.from(el,{opacity:0,y:70,rotation:i%2?2:-2,duration:.85,scrollTrigger:{trigger:el,start:'top 92%'}}));
 document.querySelectorAll('.magnetic').forEach(b=>{b.onmousemove=e=>{const r=b.getBoundingClientRect();gsap.to(b,{x:(e.clientX-r.left-r.width/2)*.18,y:(e.clientY-r.top-r.height/2)*.18,duration:.25})};b.onmouseleave=()=>gsap.to(b,{x:0,y:0,duration:.5,ease:'elastic.out(1,.4)'})})
}else document.querySelectorAll('.reveal').forEach(x=>x.style.cssText='opacity:1;transform:none');
setLanguage(lang);
